### ISSUE TITLE
`--mcp` fails in Bun compiled binaries: stdio transport import is invisible to bundlers

### ISSUE THREAD

**Issue by jwondrusch** [wevm/incur#225]
🤖 *Filed by jwondrusch's AI agent.*

## Repro

Compile a CLI that uses `mcp:` options with `bun build --compile`, then run it with `--mcp`:

```
error: Cannot find module '@modelcontextprotocol/server/stdio' from '/$bunfs/root/<binary>'
```

Affects at least 0.4.19 → 0.4.26 (current latest). The same CLI works under `node`/`tsx` with node_modules present, and issue #72 / PR #73 suggest Bun compiled binaries are an intended target, so filing this as a gap.

## Root cause

`src/Mcp.ts` reaches the stdio transport through a wrapper introduced in #175:

```ts
const importModule = (specifier: string): Promise<unknown> => import(specifier)
// ...
return importModule('@modelcontextprotocol/server/stdio')
```

Because the specifier flows through a function parameter, bundlers can't statically analyze the import, so `bun build --compile` never embeds `@modelcontextprotocol/server/stdio` in the executable — and at runtime there is no node_modules to fall back on inside `$bunfs`. (The root-module import on the line above it is a literal, so it bundles fine; but `@modelcontextprotocol/server@2.0.0-alpha.4`'s root export does not include `StdioServerTransport`, so the subpath fallback is always taken and always fails.)

## Suggested fix

Use a literal dynamic import:

```ts
return import('@modelcontextprotocol/server/stdio')
```

This keeps MCP startup lazy at runtime (the concern #175 solved is unaffected — the `.catch` fallback still tolerates SDK versions where the subpath doesn't resolve) while making the specifier visible to static analysis so Bun embeds the module.

We're currently shipping exactly this as a pnpm patch on 0.4.26 and can confirm it fixes `--mcp` in compiled binaries with no regression to the node/tsx paths.
